import { createClient } from '@libsql/client'
import { drizzle } from 'drizzle-orm/libsql'
import * as schema from './schema'

const client = createClient({
  url: process.env.TURSO_DATABASE_URL || 'file:local.db',
  authToken: process.env.TURSO_AUTH_TOKEN,
})

const db = drizzle(client, { schema })

const seedCreatives = [
  {
    slug: 'elena-vasquez',
    name: 'Elena Vasquez',
    title: 'AI Visual Artist',
    category: 'ai-artist' as const,
    bio: 'Pioneering the intersection of machine learning and fine art. Elena creates dreamlike landscapes using custom-trained diffusion models, blending Renaissance composition with algorithmic chaos.',
    avatar: 'https://picsum.photos/seed/elena/400/400',
    location: 'Barcelona, Spain',
    featured: true,
    tags: ['Diffusion Models', 'Fine Art', 'Landscapes'],
    links: [{ label: 'Portfolio', url: '#' }, { label: 'Instagram', url: '#' }, { label: 'Twitter', url: '#' }],
    portfolio: [
      { title: 'Neural Horizons', image: 'https://picsum.photos/seed/elena1/800/600', description: 'AI-generated landscape series exploring the boundary between real and synthetic nature.' },
      { title: 'Digital Bloom', image: 'https://picsum.photos/seed/elena2/800/600', description: 'Floral compositions created through iterative diffusion processes.' },
      { title: 'Synthetic Portraits', image: 'https://picsum.photos/seed/elena3/600/800', description: 'A study in AI-generated human expression and emotion.' },
    ],
  },
  {
    slug: 'marcus-chen',
    name: 'Marcus Chen',
    title: 'Creative Technologist & Builder',
    category: 'builder' as const,
    bio: 'Full-stack engineer building the tools that empower the next generation of digital creators. From real-time collaboration platforms to generative design systems.',
    avatar: 'https://picsum.photos/seed/marcus/400/400',
    location: 'San Francisco, CA',
    featured: true,
    tags: ['WebGL', 'Creative Tools', 'Open Source'],
    links: [{ label: 'GitHub', url: '#' }, { label: 'Website', url: '#' }, { label: 'LinkedIn', url: '#' }],
    portfolio: [
      { title: 'CanvasSync', image: 'https://picsum.photos/seed/marcus1/800/600', description: 'Real-time collaborative design tool for distributed creative teams.' },
      { title: 'GenUI Kit', image: 'https://picsum.photos/seed/marcus2/800/600', description: 'AI-powered component library that generates UI from natural language.' },
      { title: 'Pixel Engine', image: 'https://picsum.photos/seed/marcus3/800/600', description: 'WebGL rendering engine optimized for generative art applications.' },
    ],
  },
  {
    slug: 'aiko-tanaka',
    name: 'Aiko Tanaka',
    title: 'Senior Brand Designer',
    category: 'designer' as const,
    bio: 'Crafting visual identities that tell compelling stories. 10+ years of experience working with tech startups, cultural institutions, and luxury brands across Tokyo and New York.',
    avatar: 'https://picsum.photos/seed/aiko/400/400',
    location: 'Tokyo, Japan',
    featured: true,
    tags: ['Branding', 'UI/UX', 'Typography'],
    links: [{ label: 'Behance', url: '#' }, { label: 'Dribbble', url: '#' }, { label: 'Website', url: '#' }],
    portfolio: [
      { title: 'Mori Museum Rebrand', image: 'https://picsum.photos/seed/aiko1/800/600', description: 'Complete visual identity redesign for a contemporary art museum.' },
      { title: 'Zenith App Design', image: 'https://picsum.photos/seed/aiko2/800/600', description: 'Product design for a meditation and wellness application.' },
      { title: 'Kyoto Heritage', image: 'https://picsum.photos/seed/aiko3/800/600', description: 'Brand system for a traditional craft preservation initiative.' },
    ],
  },
  {
    slug: 'omar-hassan',
    name: 'Omar Hassan',
    title: 'Generative AI Artist',
    category: 'ai-artist' as const,
    bio: 'Exploring the boundaries of human creativity and artificial intelligence. Omar uses GANs and custom neural networks to create immersive digital installations.',
    avatar: 'https://picsum.photos/seed/omar/400/400',
    location: 'Berlin, Germany',
    featured: false,
    tags: ['GANs', 'Installations', 'Generative'],
    links: [{ label: 'Website', url: '#' }, { label: 'Twitter', url: '#' }],
    portfolio: [
      { title: 'Fractal Dreams', image: 'https://picsum.photos/seed/omar1/800/600', description: 'Infinite zoom animations generated by recursive neural networks.' },
      { title: 'Data Portraits', image: 'https://picsum.photos/seed/omar2/600/800', description: 'Portraits composed from personal data streams and social media footprints.' },
      { title: 'Sound to Vision', image: 'https://picsum.photos/seed/omar3/800/600', description: 'Real-time audio visualization using AI-driven particle systems.' },
    ],
  },
  {
    slug: 'priya-sharma',
    name: 'Priya Sharma',
    title: 'Motion Designer',
    category: 'designer' as const,
    bio: 'Bringing brands to life through motion. Priya creates kinetic typography, animated logos, and immersive brand experiences for global clients.',
    avatar: 'https://picsum.photos/seed/priya/400/400',
    location: 'Mumbai, India',
    featured: false,
    tags: ['Motion', 'Animation', 'After Effects'],
    links: [{ label: 'Vimeo', url: '#' }, { label: 'Instagram', url: '#' }, { label: 'Website', url: '#' }],
    portfolio: [
      { title: 'Nike Flow', image: 'https://picsum.photos/seed/priya1/800/600', description: "Kinetic brand experience for Nike's sustainable line." },
      { title: 'Spotify Wrapped 2025', image: 'https://picsum.photos/seed/priya2/800/600', description: "Custom animation system for Spotify's annual recap." },
      { title: 'Abstract Loops', image: 'https://picsum.photos/seed/priya3/800/600', description: 'Personal project exploring infinite animation loops.' },
    ],
  },
  {
    slug: 'james-wright',
    name: 'James Wright',
    title: 'Full-Stack Builder',
    category: 'builder' as const,
    bio: 'Building beautiful, performant web applications that push creative boundaries. Specializing in immersive 3D web experiences and creative development.',
    avatar: 'https://picsum.photos/seed/james/400/400',
    location: 'London, UK',
    featured: false,
    tags: ['Three.js', 'WebGL', 'Creative Dev'],
    links: [{ label: 'GitHub', url: '#' }, { label: 'Website', url: '#' }, { label: 'Twitter', url: '#' }],
    portfolio: [
      { title: 'Immersive Gallery', image: 'https://picsum.photos/seed/james1/800/600', description: 'WebGL-powered virtual art gallery with spatial audio.' },
      { title: 'Shader Playground', image: 'https://picsum.photos/seed/james2/800/600', description: 'Interactive GLSL shader editor with live preview and sharing.' },
      { title: 'Creative CMS', image: 'https://picsum.photos/seed/james3/800/600', description: 'Headless CMS designed specifically for portfolio and gallery sites.' },
    ],
  },
  {
    slug: 'luna-park',
    name: 'Luna Park',
    title: 'AI Art Director',
    category: 'ai-artist' as const,
    bio: 'Former advertising art director turned AI art pioneer. Luna curates and directs AI-generated visual campaigns that blur the line between commercial and fine art.',
    avatar: 'https://picsum.photos/seed/luna/400/400',
    location: 'Seoul, South Korea',
    featured: false,
    tags: ['Art Direction', 'Midjourney', 'Fashion'],
    links: [{ label: 'Instagram', url: '#' }, { label: 'Website', url: '#' }],
    portfolio: [
      { title: 'Synthetic Fashion', image: 'https://picsum.photos/seed/luna1/600/800', description: 'AI-generated fashion editorials for major publications.' },
      { title: 'Neon Dreams', image: 'https://picsum.photos/seed/luna2/800/600', description: 'Cyberpunk-inspired cityscape series created with Midjourney and Photoshop.' },
      { title: 'Brand AI', image: 'https://picsum.photos/seed/luna3/800/600', description: 'AI-directed brand identity exploration for tech startups.' },
    ],
  },
  {
    slug: 'diego-morales',
    name: 'Diego Morales',
    title: 'UX/UI Designer',
    category: 'designer' as const,
    bio: 'Designing human-centered digital experiences. Diego combines research-driven design with a keen aesthetic sensibility to create products people love to use.',
    avatar: 'https://picsum.photos/seed/diego/400/400',
    location: 'Mexico City, Mexico',
    featured: false,
    tags: ['UX Research', 'Product Design', 'Design Systems'],
    links: [{ label: 'Dribbble', url: '#' }, { label: 'LinkedIn', url: '#' }, { label: 'Website', url: '#' }],
    portfolio: [
      { title: 'Health+ App', image: 'https://picsum.photos/seed/diego1/800/600', description: 'Complete UX redesign of a health tracking application.' },
      { title: 'Fintech Dashboard', image: 'https://picsum.photos/seed/diego2/800/600', description: 'Data visualization dashboard for a cryptocurrency platform.' },
      { title: 'Travel Companion', image: 'https://picsum.photos/seed/diego3/800/600', description: 'AI-powered travel planning app with personalized itineraries.' },
    ],
  },
  {
    slug: 'sarah-kim',
    name: 'Sarah Kim',
    title: 'Creative Engineer',
    category: 'builder' as const,
    bio: 'Building at the intersection of code and creativity. Sarah creates open-source tools for generative art, interactive installations, and creative coding education.',
    avatar: 'https://picsum.photos/seed/sarah/400/400',
    location: 'Portland, OR',
    featured: false,
    tags: ['Creative Coding', 'Open Source', 'Education'],
    links: [{ label: 'GitHub', url: '#' }, { label: 'Website', url: '#' }, { label: 'YouTube', url: '#' }],
    portfolio: [
      { title: 'Generative.js', image: 'https://picsum.photos/seed/sarah1/800/600', description: 'Open-source library for creating generative art in the browser.' },
      { title: 'Code Canvas', image: 'https://picsum.photos/seed/sarah2/800/600', description: 'Interactive creative coding playground for beginners.' },
      { title: 'Data Sculpture', image: 'https://picsum.photos/seed/sarah3/800/600', description: 'Physical computing installation translating live data into kinetic sculpture.' },
    ],
  },
]

async function seed() {
  console.log('Seeding database...')

  for (const data of seedCreatives) {
    const { portfolio, ...creativeData } = data

    const [creative] = await db.insert(schema.creatives).values(creativeData).returning()
    console.log(`  Created: ${creative.name}`)

    for (let i = 0; i < portfolio.length; i++) {
      await db.insert(schema.portfolioItems).values({
        creativeId: creative.id,
        title: portfolio[i].title,
        image: portfolio[i].image,
        description: portfolio[i].description,
        sortOrder: i,
      })
    }
  }

  console.log(`Seeded ${seedCreatives.length} creatives.`)
}

seed().catch(console.error)
